RegisterNetEvent("gcPhone:tchat_receive")
AddEventHandler("gcPhone:tchat_receive", function(message)
    SendNUIMessage({ event = 'tchat_receive', message = message })
    cb(true)
end)

RegisterNetEvent("gcPhone:tchat_channel")
AddEventHandler("gcPhone:tchat_channel", function(channel, messages)
    SendNUIMessage({ event = 'tchat_channel', messages = messages })
    cb(true)
end)

RegisterNUICallback('tchat_addMessage', function(data, cb)
    TriggerServerEvent('gcPhone:tchat_addMessage', data.channel, data.message)
    cb(true)
end)

RegisterNUICallback('tchat_getChannel', function(data, cb)
    TriggerServerEvent('gcPhone:tchat_channel', data.channel)
    cb(true)
end)
